version: '3.8'

services:
  web:
    build: .
    command: bash -c "source venv/bin/activate && python app.py"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
      - MS_API_KEY=
      - MS_CLIENT_ID=
      - MS_CLIENT_SECRET=
      - MS_TENANT_ID=
      - ZEEV_KEY=
    depends_on:
      - redis
      - celery-worker

  celery-worker:
    build: .
    command: bash -c "source venv/bin/activate && celery -A main worker --loglevel=info"
    volumes:
      - .:/app
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 
